# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/griff/Median Filter/Median Filter.srcs/sources_1/ip/fifo_buffer/fifo_buffer.xci
# IP: The module: 'fifo_buffer' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/griff/Median Filter/Median Filter.gen/sources_1/ip/fifo_buffer/fifo_buffer.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_buffer'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/griff/Median Filter/Median Filter.gen/sources_1/ip/fifo_buffer/fifo_buffer_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_buffer'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/griff/Median Filter/Median Filter.srcs/sources_1/ip/fifo_buffer/fifo_buffer.xci
# IP: The module: 'fifo_buffer' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/griff/Median Filter/Median Filter.gen/sources_1/ip/fifo_buffer/fifo_buffer.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_buffer'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/griff/Median Filter/Median Filter.gen/sources_1/ip/fifo_buffer/fifo_buffer_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_buffer'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
